/**
 * SizeChartStep - Etapa de Tabela de Medidas e Cuidados
 * Aparece condicionalmente após variações (só para calçado e roupas)
 * Gera automaticamente baseado nas variações e permite customização
 */

import React, { useState, useEffect, useMemo } from 'react';
import { WizardFormData } from '@/hooks/useImprovedProductFormWizard';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  Ruler, 
  Plus, 
  Trash2, 
  RefreshCw, 
  CheckCircle,
  AlertTriangle,
  Heart,
  Info,
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface SizeData {
  size: string;
  br: string;
  us: string;
  eu: string;
  cm?: string;
}

interface CareInstruction {
  id: string;
  type: 'do' | 'dont' | 'warning';
  icon: string;
  instruction: string;
}

interface SizeChartStepProps {
  formData: WizardFormData;
  updateFormData: (updates: Partial<WizardFormData>) => void;
}

const SizeChartStep: React.FC<SizeChartStepProps> = ({ formData, updateFormData }) => {
  const [customSizes, setCustomSizes] = useState<SizeData[]>([]);
  const [careInstructions, setCareInstructions] = useState<CareInstruction[]>([]);
  const [useAutoGenerated, setUseAutoGenerated] = useState(true);

  // Extrair tamanhos das variações
  const variationSizes = useMemo(() => {
    if (!formData.variations || formData.variations.length === 0) return [];
    
    const sizes = new Set<string>();
    formData.variations.forEach(variation => {
      if (variation.size) {
        sizes.add(variation.size);
      }
    });
    
    return Array.from(sizes).sort((a, b) => {
      const numA = parseInt(a);
      const numB = parseInt(b);
      if (!isNaN(numA) && !isNaN(numB)) {
        return numA - numB;
      }
      return a.localeCompare(b);
    });
  }, [formData.variations]);

  // Gerar tabela automática baseada nas variações
  const autoGeneratedSizes = useMemo(() => {
    if (variationSizes.length === 0) return [];

    const isNumericSize = variationSizes.every(size => !isNaN(parseInt(size)));
    
    if (!isNumericSize) {
      // Tamanhos tipo PP, P, M, G, GG
      return variationSizes.map(size => ({
        size,
        br: size,
        us: size === 'PP' ? 'XS' : size === 'P' ? 'S' : size === 'M' ? 'M' : size === 'G' ? 'L' : 'XL',
        eu: size === 'PP' ? 'XS' : size === 'P' ? 'S' : size === 'M' ? 'M' : size === 'G' ? 'L' : 'XL',
        cm: undefined,
      }));
    }

    // Tamanhos numéricos - detectar se é calçado ou roupa
    const minSize = Math.min(...variationSizes.map(s => parseInt(s)));
    const maxSize = Math.max(...variationSizes.map(s => parseInt(s)));

    // Se é calçado (números geralmente 18-45)
    if (minSize >= 18 && maxSize <= 45) {
      return variationSizes.map(size => {
        const sizeNum = parseInt(size);
        const isInfantil = sizeNum <= 34;
        
        return {
          size,
          br: size,
          us: isInfantil 
            ? `${Math.floor((sizeNum - 18) / 2)}C`
            : `${Math.floor((sizeNum - 32) / 2)}`,
          eu: size,
          cm: (12 + (sizeNum - 18) * 0.5).toFixed(1),
        };
      });
    }

    // Roupas com números
    return variationSizes.map(size => ({
      size,
      br: size,
      us: size,
      eu: size,
      cm: undefined,
    }));
  }, [variationSizes]);

  // Gerar instruções de cuidado automáticas
  const autoGeneratedCare = useMemo(() => {
    const instructions: CareInstruction[] = [];
    const category = formData.product_category_type;
    const material = formData.material?.toLowerCase() || '';

    if (category === 'calcado') {
      instructions.push(
        {
          id: '1',
          type: 'do',
          icon: 'water',
          instruction: 'Limpe com pano úmido e sabão neutro',
        },
        {
          id: '2',
          type: 'do',
          icon: 'dry',
          instruction: 'Seque à sombra em local arejado',
        },
        {
          id: '3',
          type: 'dont',
          icon: 'wash',
          instruction: 'Não lave em máquina de lavar',
        },
        {
          id: '4',
          type: 'dont',
          icon: 'sun',
          instruction: 'Não exponha ao sol direto por longos períodos',
        }
      );

      if (material.includes('couro') || material.includes('sintético')) {
        instructions.push({
          id: '5',
          type: 'do',
          icon: 'protect',
          instruction: 'Use impermeabilizante para proteção',
        });
      }
    } else if (category === 'roupa_superior' || category === 'roupa_inferior') {
      instructions.push(
        {
          id: '1',
          type: 'do',
          icon: 'wash',
          instruction: 'Lave com cores semelhantes',
        },
        {
          id: '2',
          type: 'do',
          icon: 'water',
          instruction: 'Use água fria ou morna (máx. 30°C)',
        }
      );

      // Tecidos delicados
      if (material.includes('seda') || material.includes('linho') || material.includes('lã')) {
        instructions.push({
          id: '3',
          type: 'warning',
          icon: 'wash',
          instruction: 'Lave no modo delicado ou à mão',
        });
      } else {
        instructions.push({
          id: '3',
          type: 'do',
          icon: 'wash',
          instruction: 'Pode lavar em máquina no modo normal',
        });
      }

      instructions.push(
        {
          id: '4',
          type: 'do',
          icon: 'dry',
          instruction: 'Seque à sombra',
        },
        {
          id: '5',
          type: 'dont',
          icon: 'bleach',
          instruction: 'Não use alvejante',
        }
      );

      // Passar roupa
      if (material.includes('algodão') || material.includes('linho')) {
        instructions.push({
          id: '6',
          type: 'do',
          icon: 'iron',
          instruction: 'Pode passar em temperatura média',
        });
      } else {
        instructions.push({
          id: '6',
          type: 'dont',
          icon: 'iron',
          instruction: 'Não passe em temperatura alta',
        });
      }
    }

    return instructions;
  }, [formData.product_category_type, formData.material]);

  // Inicializar com dados auto-gerados
  useEffect(() => {
    if (useAutoGenerated) {
      setCustomSizes(autoGeneratedSizes);
      setCareInstructions(autoGeneratedCare);
    }
  }, [useAutoGenerated, autoGeneratedSizes, autoGeneratedCare]);

  const displaySizes = useAutoGenerated ? autoGeneratedSizes : customSizes;
  const displayCare = useAutoGenerated ? autoGeneratedCare : careInstructions;

  const isShoe = formData.product_category_type === 'calcado';

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-lg font-semibold">Tabela de Medidas e Cuidados</h3>
          <p className="text-sm text-muted-foreground mt-1">
            Gerado automaticamente baseado nas variações e tipo do produto
          </p>
        </div>
        <Badge variant="secondary" className="bg-indigo-100 text-indigo-700">
          📏 Auto-gerado
        </Badge>
      </div>

      {/* Aviso se não tiver variações */}
      {variationSizes.length === 0 && (
        <Alert className="border-yellow-300 bg-yellow-50">
          <AlertTriangle className="h-4 w-4 text-yellow-600" />
          <AlertDescription className="text-yellow-900">
            <strong>Atenção:</strong> Nenhum tamanho encontrado nas variações. Cadastre variações com tamanhos para gerar a tabela automaticamente.
          </AlertDescription>
        </Alert>
      )}

      {/* Tabela de Medidas */}
      {variationSizes.length > 0 && (
        <Card>
          <CardHeader className="bg-gradient-to-r from-indigo-50 to-purple-50">
            <div className="flex items-center justify-between">
              <CardTitle className="text-lg flex items-center gap-2">
                <Ruler className="w-5 h-5 text-indigo-600" />
                Tabela de Medidas
              </CardTitle>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setUseAutoGenerated(!useAutoGenerated)}
              >
                <RefreshCw className="w-4 h-4 mr-2" />
                {useAutoGenerated ? 'Personalizar' : 'Usar Auto-gerado'}
              </Button>
            </div>
          </CardHeader>
          <CardContent className="p-4">
            <Alert className="mb-4 bg-blue-50 border-blue-200">
              <Info className="h-4 w-4 text-blue-600" />
              <AlertDescription className="text-blue-900 text-sm">
                <strong>Detectado:</strong> {variationSizes.length} tamanho(s) ({variationSizes.join(', ')})
                {isShoe && ' - Calçado'}
                {formData.product_gender && ` - ${formData.product_gender}`}
              </AlertDescription>
            </Alert>

            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b-2 border-gray-300">
                    <th className="text-left py-3 px-2 font-semibold">Tamanho</th>
                    <th className="text-center py-3 px-2 font-semibold">BR</th>
                    <th className="text-center py-3 px-2 font-semibold">US</th>
                    <th className="text-center py-3 px-2 font-semibold">EU</th>
                    {isShoe && (
                      <th className="text-center py-3 px-2 font-semibold">CM</th>
                    )}
                  </tr>
                </thead>
                <tbody>
                  {displaySizes.map((size, index) => (
                    <tr 
                      key={size.size}
                      className={`border-b border-gray-200 hover:bg-gray-50 ${
                        index % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'
                      }`}
                    >
                      <td className="py-2 px-2 font-semibold">{size.size}</td>
                      <td className="text-center py-2 px-2">{size.br}</td>
                      <td className="text-center py-2 px-2">{size.us}</td>
                      <td className="text-center py-2 px-2">{size.eu}</td>
                      {isShoe && (
                        <td className="text-center py-2 px-2">{size.cm}</td>
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="mt-4 p-3 bg-green-50 rounded-lg border border-green-200">
              <p className="text-sm text-green-900 font-medium flex items-center gap-2">
                <CheckCircle className="w-4 h-4" />
                Tabela gerada para {displaySizes.length} tamanho(s) baseado nas suas variações
              </p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Instruções de Cuidado */}
      <Card>
        <CardHeader className="bg-gradient-to-r from-teal-50 to-cyan-50">
          <CardTitle className="text-lg flex items-center gap-2">
            <Heart className="w-5 h-5 text-teal-600" />
            Instruções de Cuidado
          </CardTitle>
        </CardHeader>
        <CardContent className="p-4">
          <Alert className="mb-4 bg-teal-50 border-teal-200">
            <Info className="h-4 w-4 text-teal-600" />
            <AlertDescription className="text-teal-900 text-sm">
              <strong>Auto-gerado baseado em:</strong> {formData.product_category_type || 'Tipo não definido'}
              {formData.material && ` - ${formData.material}`}
            </AlertDescription>
          </Alert>

          <div className="space-y-3">
            {/* O que FAZER */}
            <div>
              <h4 className="font-semibold text-green-900 mb-2 flex items-center gap-2 text-sm">
                <CheckCircle className="w-4 h-4 text-green-600" />
                ✅ Cuidados Recomendados
              </h4>
              <div className="space-y-2">
                {displayCare.filter(c => c.type === 'do').map((care) => (
                  <div 
                    key={care.id}
                    className="flex items-start gap-2 text-sm text-gray-700 bg-green-50 p-2 rounded-lg border border-green-200"
                  >
                    <span className="text-green-600 mt-0.5">•</span>
                    <span>{care.instruction}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* O que NÃO FAZER */}
            <div>
              <h4 className="font-semibold text-red-900 mb-2 flex items-center gap-2 text-sm">
                <AlertTriangle className="w-4 h-4 text-red-600" />
                ❌ Evite
              </h4>
              <div className="space-y-2">
                {displayCare.filter(c => c.type === 'dont').map((care) => (
                  <div 
                    key={care.id}
                    className="flex items-start gap-2 text-sm text-gray-700 bg-red-50 p-2 rounded-lg border border-red-200"
                  >
                    <span className="text-red-600 mt-0.5">•</span>
                    <span>{care.instruction}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* AVISOS */}
            {displayCare.filter(c => c.type === 'warning').length > 0 && (
              <div>
                <h4 className="font-semibold text-orange-900 mb-2 flex items-center gap-2 text-sm">
                  <AlertTriangle className="w-4 h-4 text-orange-600" />
                  ⚠️ Atenção
                </h4>
                <div className="space-y-2">
                  {displayCare.filter(c => c.type === 'warning').map((care) => (
                    <div 
                      key={care.id}
                      className="flex items-start gap-2 text-sm text-gray-700 bg-orange-50 p-2 rounded-lg border border-orange-200"
                    >
                      <span className="text-orange-600 mt-0.5">•</span>
                      <span>{care.instruction}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="mt-4 p-3 bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg border border-purple-200">
            <p className="text-sm text-purple-900">
              <strong>💡 Dica:</strong> Estas instruções serão exibidas automaticamente na página do produto para seus clientes.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Resumo */}
      <Alert className="bg-gradient-to-r from-green-50 to-emerald-50 border-green-300">
        <CheckCircle className="h-5 w-5 text-green-600" />
        <AlertDescription className="text-green-900">
          <strong>Tudo pronto!</strong> Tabela de medidas e instruções de cuidado geradas automaticamente.
          {variationSizes.length > 0 && (
            <span> Seus clientes verão {displaySizes.length} tamanho(s) e {displayCare.length} instrução(ões) de cuidado.</span>
          )}
        </AlertDescription>
      </Alert>
    </div>
  );
};

export default SizeChartStep;

